version: '3.7'
services:
  web:
    image: djangoapp
    restart: always
    build:
      context: ./source
      dockerfile: Dockerfile
    command: gunicorn source.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/source/web/staticfiles
      - media_volume:/home/source/web/mediafiles
      - .:/app
  nginx:
    restart: always
    build: ./nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/home/source/web/staticfiles
      - media_volume:/home/source/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:


#networks:
#  elasticnetwork:
#    driver: bridge
#  kibananet:
#    driver: bridge
